// Generates src/app/pixel-frames.css: 9-slice pixel frames as inline SVG (3 px cells on a 9x9 grid).
// Outer ring = frame colour with notched corners, second ring = bevel (light top/left, dark bottom/right),
// the rest = fill. Used with `border: 9px solid transparent; border-image: … 9 fill stretch`.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const PX = 3;
const N = 9;

const VARIANTS = [
  { name: 'night', outer: '#3b3a45', light: '#4a4956', dark: '#121318', fill: '#1d1f26' },
  { name: 'work', outer: '#add064', light: '#d6ef9c', dark: '#6f8f3a', fill: '#1d1f26' },
  { name: 'green', outer: '#07070a', light: '#a3dc7c', dark: '#3f7a2e', fill: '#65b24c' },
  { name: 'ghost', outer: '#07070a', light: '#4a4956', dark: '#121318', fill: '#2b2d33' },
  { name: 'input', outer: '#3b3a45', light: '#121318', dark: '#4a4956', fill: '#07070a' },
];

function svg({ outer, light, dark, fill }) {
  const rects = [];
  for (let y = 0; y < N; y++) {
    for (let x = 0; x < N; x++) {
      const corner = (x === 0 || x === N - 1) && (y === 0 || y === N - 1);
      if (corner) continue;
      const ring = Math.min(x, y, N - 1 - x, N - 1 - y);
      let colour = fill;
      if (ring === 0) colour = outer;
      else if (ring === 1) colour = y === 1 || x === 1 ? light : dark;
      rects.push(`<rect x="${x * PX}" y="${y * PX}" width="${PX}" height="${PX}" fill="${colour}"/>`);
    }
  }
  const size = N * PX;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" shape-rendering="crispEdges">${rects.join('')}</svg>`;
}

const css = [
  '/* Generated by scripts/gen-frames.mjs. Do not edit. */',
  '.frame {',
  '  border: 9px solid transparent;',
  '  border-image-slice: 9 fill;',
  '  border-image-repeat: stretch;',
  '  image-rendering: pixelated;',
  '}',
  ...VARIANTS.map((v) => `.frame--${v.name} {\n  border-image-source: url("data:image/svg+xml,${encodeURIComponent(svg(v))}");\n}`),
  '',
].join('\n');

const out = fileURLToPath(new URL('../src/app/pixel-frames.css', import.meta.url));
writeFileSync(out, css);
console.log(`wrote ${out} (${VARIANTS.length} frames)`);
