#!/usr/bin/env bash
# Exports contract ABIs as typed TS constants for viem. Run after changing contracts/src.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/web/src/chain/abi"
mkdir -p "$OUT"
cd "$ROOT/contracts"
forge build --silent
for NAME in HashMine PonsTreasury; do
  LOWER="$(echo "${NAME:0:1}" | tr '[:upper:]' '[:lower:]')${NAME:1}"
  ABI="$(forge inspect "$NAME" abi --json)"
  printf '// Generated by scripts/export-abi.sh from contracts/src/%s.sol. Do not edit.\nexport const %sAbi = %s as const;\n' "$NAME" "$LOWER" "$ABI" > "$OUT/$LOWER.ts"
  echo "wrote $OUT/$LOWER.ts"
done
